; PlatformIO Project Configuration File
; SBUS -> BLE HID Gamepad Bridge
; Target: ESP32-C3 Super Mini (Tenstar Robot)

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    C:\Users\snyder\Documents\Arduino\libraries\Bolder_Flight_Systems_SBUS
    C:\Users\snyder\Documents\Arduino\libraries\Adafruit_NeoPixel
    lemmingdev/ESP32-BLE-Gamepad
